name: Site CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check-pull-request:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Test Build
        run: |
          npm install
          npm run build

  github-pages-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to GitHub Pages
        run: npx docusaurus deploy
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
